#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################
services:
  spring-petclinic-svc:
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 2
#      resources:
#        limits:
#          cpus: "0.5"
#          memory: "1Gi"
#        reservations:
#          cpus: "0.5"
#          memory: "1Gi"
    image: openshiftacademiaonline/spring-petclinic-dev:latest
    ports:
      - 8080:8080
version: '3.8'
#########################################################################
