#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################
services:
  spring-petclinic-svc:
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 2
    image: openshiftacademiaonline/spring-petclinic-dev:latest
    ports:
      - 80:8080
version: '3.8'
#########################################################################
